const employees = [
  {
    id: 1,
    email: "employee1@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Complete Dashboard UI",
        taskDescription: "Build the employee dashboard with responsive layout and reusable components.",
        taskDate: "2026-09-04",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix Login Validation",
        taskDescription: "Resolve validation issues in the employee login form.",
        taskDate: "2026-09-05",
        category: "Bug Fix",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Setup Project Repository",
        taskDescription: "Initialize the repository and configure the basic project structure.",
        taskDate: "2026-09-01",
        category: "Setup",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Prepare API Documentation",
        taskDescription: "Create documentation for all available REST API endpoints.",
        taskDate: "2026-09-02",
        category: "Documentation",
      },
    ],
  },

  {
    id: 2,
    email: "employee2@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Implement User Authentication",
        taskDescription: "Implement login and logout functionality using the existing authentication API.",
        taskDate: "2026-09-04",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create User Profile Page",
        taskDescription: "Develop the profile page where users can view and update their information.",
        taskDate: "2026-09-06",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Database Schema Design",
        taskDescription: "Design the database schema required for employee and task management.",
        taskDate: "2026-09-01",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Test API Endpoints",
        taskDescription: "Test authentication and task management endpoints using Postman.",
        taskDate: "2026-09-02",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Deploy Staging Server",
        taskDescription: "Deploy the latest application build to the staging environment.",
        taskDate: "2026-09-03",
        category: "Deployment",
      },
    ],
  },

  {
    id: 3,
    email: "employee3@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Build Task Management API",
        taskDescription: "Create REST APIs for creating, updating, deleting, and retrieving tasks.",
        taskDate: "2026-09-04",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Add Task Filtering",
        taskDescription: "Add filtering functionality based on task category and status.",
        taskDate: "2026-09-05",
        category: "Development",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Configure Express Server",
        taskDescription: "Configure the Express server and establish the initial API structure.",
        taskDate: "2026-08-30",
        category: "Backend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create MongoDB Models",
        taskDescription: "Create database models for users and tasks.",
        taskDate: "2026-09-01",
        category: "Database",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Implement Email Notifications",
        taskDescription: "Add email notifications for task assignments and deadlines.",
        taskDate: "2026-09-02",
        category: "Integration",
      },
    ],
  },

  {
    id: 4,
    email: "employee4@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Design Analytics Dashboard",
        taskDescription: "Create the UI for displaying employee and task performance metrics.",
        taskDate: "2026-09-04",
        category: "Design",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Create Performance Charts",
        taskDescription: "Implement charts for completed, active, and failed tasks.",
        taskDate: "2026-09-05",
        category: "Frontend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Add Responsive Layout",
        taskDescription: "Make the dashboard responsive across desktop, tablet, and mobile devices.",
        taskDate: "2026-09-06",
        category: "Frontend",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Create Dashboard Wireframe",
        taskDescription: "Prepare the initial wireframe for the analytics dashboard.",
        taskDate: "2026-09-01",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review UI Components",
        taskDescription: "Review existing UI components and identify reusable elements.",
        taskDate: "2026-09-02",
        category: "Review",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Implement Dark Mode",
        taskDescription: "Add dark mode support to the application interface.",
        taskDate: "2026-09-03",
        category: "Frontend",
      },
    ],
  },

  {
    id: 5,
    email: "employee5@example.com",
    password: "123",
    tasks: [
      {
        active: true,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Write Unit Tests",
        taskDescription: "Write unit tests for the authentication and task management modules.",
        taskDate: "2026-09-04",
        category: "Testing",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Fix API Error Handling",
        taskDescription: "Improve API error handling and return meaningful HTTP responses.",
        taskDate: "2026-09-05",
        category: "Backend",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Perform Integration Testing",
        taskDescription: "Test communication between frontend, backend, and database services.",
        taskDate: "2026-09-07",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Setup Testing Environment",
        taskDescription: "Configure the testing environment and required dependencies.",
        taskDate: "2026-09-01",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Review Test Coverage",
        taskDescription: "Analyze existing test coverage and identify missing test cases.",
        taskDate: "2026-09-02",
        category: "Testing",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Performance Testing",
        taskDescription: "Run performance tests and identify slow API operations.",
        taskDate: "2026-09-03",
        category: "Performance",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Prepare Testing Report",
        taskDescription: "Document testing results, issues, and recommended fixes.",
        taskDate: "2026-09-03",
        category: "Documentation",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@example.com",
    password: "123",
  },
];




export const setLocalStorage = function(){
    localStorage.setItem('employees', JSON.stringify(employees))
    localStorage.setItem('admin', JSON.stringify(admin))
}

export const getLocalStorage = function(){
    const employees = JSON.parse(localStorage.getItem('employees'))
    const admin = JSON.parse(localStorage.getItem('admin'))
    console.log(admin,employees)
}